# Generated by Django 5.2.17 on 2026-08-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("facturacion", "0001_initial"),
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="orden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facturas",
                to="ordenes.ordentrabajo",
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="taller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.taller",
            ),
        ),
        migrations.AddField(
            model_name="detallefactura",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="facturacion.factura",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="facturacion.factura",
            ),
        ),
        migrations.AddConstraint(
            model_name="factura",
            constraint=models.UniqueConstraint(
                fields=("taller", "numero"), name="numero_factura_unico_por_taller"
            ),
        ),
    ]
