# Generated by Django 5.2.17 on 2026-08-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('facturacion', '0002_initial'),
        ('ordenes', '0004_ordentrabajo_token_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='clave_numerica',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='consecutivo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='ordenes.cotizacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estado_hacienda',
            field=models.CharField(choices=[('pendiente', 'Pendiente de envío'), ('enviada', 'Enviada, esperando respuesta'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('error', 'Error al emitir')], default='pendiente', max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha_emision_fe',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='mensaje_hacienda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor_fe',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='ConfiguracionFacturacionElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.CharField(choices=[('simulado', 'Simulado (desarrollo/demo, no llama a Hacienda)'), ('hacienda_directo', 'Hacienda directo (ATV)')], default='simulado', max_length=30)),
                ('entorno', models.CharField(choices=[('sandbox', 'Sandbox / pruebas'), ('produccion', 'Producción')], default='sandbox', max_length=15)),
                ('usuario_atv', models.CharField(blank=True, max_length=150)),
                ('contrasena_atv', models.CharField(blank=True, max_length=150)),
                ('client_id_atv', models.CharField(blank=True, default='api-stag', max_length=50)),
                ('certificado_p12_path', models.CharField(blank=True, help_text='Ruta local al .p12 en el servidor (fuera de git y de storage público). No implementado aún.', max_length=255)),
                ('certificado_p12_password', models.CharField(blank=True, max_length=150)),
                ('taller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_fe', to='core.taller')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
