# Generated by Django 5.2.17 on 2026-08-11 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0002_initial"),
        ("core", "0001_initial"),
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenTrabajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("recibido", "Recibido"),
                            ("en_diagnostico", "En diagnóstico"),
                            ("en_reparacion", "En reparación"),
                            ("esperando_repuesto", "Esperando repuesto"),
                            ("listo", "Listo"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="recibido",
                        max_length=25,
                    ),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("fecha_estimada_entrega", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega_real", models.DateTimeField(blank=True, null=True)),
                (
                    "kilometraje_ingreso",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("diagnostico", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "mecanico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "taller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.taller",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to="clientes.vehiculo",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_ingreso"],
            },
        ),
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha_hora", models.DateTimeField()),
                ("motivo", models.CharField(blank=True, max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("cumplida", "Cumplida"),
                            ("cancelada", "Cancelada"),
                            ("no_show", "No se presentó"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "taller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.taller",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="citas",
                        to="clientes.vehiculo",
                    ),
                ),
                (
                    "orden_generada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cita_origen",
                        to="ordenes.ordentrabajo",
                    ),
                ),
            ],
            options={
                "ordering": ["fecha_hora"],
            },
        ),
        migrations.CreateModel(
            name="RepuestoUsado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repuestos_usados",
                        to="ordenes.ordentrabajo",
                    ),
                ),
                (
                    "repuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usos",
                        to="inventario.repuesto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicioOrden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "horas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="ordenes.ordentrabajo",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="ordentrabajo",
            index=models.Index(
                fields=["taller", "estado"], name="ordenes_ord_taller__45229e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cita",
            index=models.Index(
                fields=["taller", "fecha_hora"], name="ordenes_cit_taller__fa87ce_idx"
            ),
        ),
    ]
