# Generated by Django 5.2.17 on 2026-08-11 23:56

import apps.ordenes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ordenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to=apps.ordenes.models.ruta_evidencia_foto)),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('diagnostico', 'Diagnóstico'), ('reparacion', 'Reparación'), ('entrega', 'Entrega')], default='ingreso', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias_foto', to='ordenes.ordentrabajo')),
                ('subida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.taller')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['taller', 'orden'], name='ordenes_evi_taller__d121db_idx')],
            },
        ),
    ]
