# Generated by Django 5.2.17 on 2026-08-12 01:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_cotizacion_detallecotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='token_seguimiento',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
