# Generated by Django 5.2.17 on 2026-08-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=150)),
                ("identificacion", models.CharField(blank=True, max_length=50)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("placa", models.CharField(max_length=20)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("anio", models.PositiveIntegerField(blank=True, null=True)),
                ("vin", models.CharField(blank=True, max_length=50)),
                ("kilometraje_actual", models.PositiveIntegerField(default=0)),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["placa"],
            },
        ),
    ]
