# Generated by Django 5.2.17 on 2026-08-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="taller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.taller",
            ),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehiculos",
                to="clientes.cliente",
            ),
        ),
        migrations.AddField(
            model_name="vehiculo",
            name="taller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.taller",
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["taller", "nombre"], name="clientes_cl_taller__bb5815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehiculo",
            index=models.Index(
                fields=["taller", "placa"], name="clientes_ve_taller__f3c324_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vehiculo",
            constraint=models.UniqueConstraint(
                fields=("taller", "placa"), name="placa_unica_por_taller"
            ),
        ),
    ]
