# Generated by Django 5.2.17 on 2026-08-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("notas", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Repuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=50)),
                ("nombre", models.CharField(max_length=150)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("unidad_medida", models.CharField(default="unidad", max_length=20)),
                (
                    "costo_promedio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "precio_venta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock_actual", models.IntegerField(default=0)),
                ("stock_minimo", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
