# Generated by Django 5.2.17 on 2026-08-11 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("inventario", "0001_initial"),
        ("ordenes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="orden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_inventario",
                to="ordenes.ordentrabajo",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="taller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.taller",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repuesto",
            name="taller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.taller",
            ),
        ),
        migrations.AddField(
            model_name="movimientoinventario",
            name="repuesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movimientos",
                to="inventario.repuesto",
            ),
        ),
        migrations.AddConstraint(
            model_name="repuesto",
            constraint=models.UniqueConstraint(
                fields=("taller", "sku"), name="sku_unico_por_taller"
            ),
        ),
    ]
